[2023-09-15T11:45:30.793+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: artis_revenue.insert_into_artist_revenue scheduled__2023-09-14T00:00:00+00:00 [queued]>
[2023-09-15T11:45:31.983+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: artis_revenue.insert_into_artist_revenue scheduled__2023-09-14T00:00:00+00:00 [queued]>
[2023-09-15T11:45:31.984+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 2
[2023-09-15T11:45:32.020+0000] {taskinstance.py:1350} INFO - Executing <Task(GenericTransfer): insert_into_artist_revenue> on 2023-09-14 00:00:00+00:00
[2023-09-15T11:45:32.047+0000] {standard_task_runner.py:57} INFO - Started process 118 to run task
[2023-09-15T11:45:32.063+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'artis_revenue', 'insert_into_artist_revenue', 'scheduled__2023-09-14T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/artist_revenue.py', '--cfg-path', '/tmp/tmp3ggzhyi7']
[2023-09-15T11:45:32.073+0000] {standard_task_runner.py:85} INFO - Job 31: Subtask insert_into_artist_revenue
[2023-09-15T11:45:32.243+0000] {task_command.py:410} INFO - Running <TaskInstance: artis_revenue.insert_into_artist_revenue scheduled__2023-09-14T00:00:00+00:00 [running]> on host ecb76d2810ac
[2023-09-15T11:45:32.439+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Imara Acacia' AIRFLOW_CTX_DAG_ID='artis_revenue' AIRFLOW_CTX_TASK_ID='insert_into_artist_revenue' AIRFLOW_CTX_EXECUTION_DATE='2023-09-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-14T00:00:00+00:00'
[2023-09-15T11:45:32.472+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-09-15T11:45:32.847+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/generic_transfer.py", line 75, in execute
    destination_hook = BaseHook.get_hook(self.destination_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 84, in get_hook
    connection = cls.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `dwh` isn't defined
[2023-09-15T11:45:32.856+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=artis_revenue, task_id=insert_into_artist_revenue, execution_date=20230914T000000, start_date=20230915T114530, end_date=20230915T114532
[2023-09-15T11:45:32.877+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 31 for task insert_into_artist_revenue (The conn_id `dwh` isn't defined; 118)
[2023-09-15T11:45:32.919+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-09-15T11:45:32.951+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
