[2023-09-07T04:13:13.806+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_operator_dag.create_pet_table scheduled__2020-02-02T00:00:00+00:00 [queued]>
[2023-09-07T04:13:13.839+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_operator_dag.create_pet_table scheduled__2020-02-02T00:00:00+00:00 [queued]>
[2023-09-07T04:13:13.841+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-09-07T04:13:13.896+0000] {taskinstance.py:1350} INFO - Executing <Task(PostgresOperator): create_pet_table> on 2020-02-02 00:00:00+00:00
[2023-09-07T04:13:13.915+0000] {standard_task_runner.py:57} INFO - Started process 85 to run task
[2023-09-07T04:13:13.927+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag', 'create_pet_table', 'scheduled__2020-02-02T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/postgres_operator.py', '--cfg-path', '/tmp/tmpk4axso0d']
[2023-09-07T04:13:13.933+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask create_pet_table
[2023-09-07T04:13:14.184+0000] {task_command.py:410} INFO - Running <TaskInstance: postgres_operator_dag.create_pet_table scheduled__2020-02-02T00:00:00+00:00 [running]> on host ecb76d2810ac
[2023-09-07T04:13:14.581+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_operator_dag' AIRFLOW_CTX_TASK_ID='create_pet_table' AIRFLOW_CTX_EXECUTION_DATE='2020-02-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-02-02T00:00:00+00:00'
[2023-09-07T04:13:14.588+0000] {sql.py:262} INFO - Executing: 
            SELECT * FROM "Album" LIMIT 10
          
[2023-09-07T04:13:14.623+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-09-07T04:13:15.263+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-09-07T04:13:15.274+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 274, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 342, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 144, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  database "public" does not exist

[2023-09-07T04:13:15.306+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=postgres_operator_dag, task_id=create_pet_table, execution_date=20200202T000000, start_date=20230907T041313, end_date=20230907T041315
[2023-09-07T04:13:15.341+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 7 for task create_pet_table (connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  database "public" does not exist
; 85)
[2023-09-07T04:13:15.393+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-09-07T04:13:15.455+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
